apiVersion: apps/v1
kind: Deployment
metadata:
  name: birdhk-nginx-deployment-test
  labels:
    app: nginxtest-test
    rd: aaa
    env: test
spec:
  selector:
    matchLabels:
      app: nginxtest-test
  replicas: 1 # 告知 Deployment 运行 2 个与该模板匹配的 Pod
  template:
    metadata:
      labels:
        app: nginxtest-test
    spec:
      containers:
        - name: nginx
          image: nginx:1.14.1
          ports:
            - containerPort: 80